# Generated by Django 2.2.6 on 2019-12-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20191222_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiessetting',
            old_name='block_activitie',
            new_name='block_activities',
        ),
    ]
