# Generated by Django 2.2.6 on 2019-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191222_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileapp',
            name='birthdate',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='facebook',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='gender',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='github',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='instagram',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='linkedin',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='location',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='multifactor_auths',
            field=models.TextField(default=None, null=True),
        ),
    ]
