# Generated by Django 3.0.2 on 2020-01-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.TextField(max_length=100)),
                ('days', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('start_time', models.IntegerField()),
            ],
        ),
    ]
