# Generated by Django 3.0.2 on 2020-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200106_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedactivities',
            name='end_time',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trackedactivities',
            name='start_time',
            field=models.TextField(max_length=100),
        ),
    ]
