# Generated by Django 3.0.2 on 2020-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activity', '0004_auto_20200106_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedactivities',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackedactivities',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
